### ISSUE TITLE
Add mapping from configuration

### ISSUE THREAD

**Issue by yoanm** [yoanm/symfony-jsonrpc-http-server#6]
```yaml
json_rpc_http_server:
  methods_mapping:
    firstMethodName: "@service.to.first_method"
    - {service: "@service.to.second_method", name: "secondMethodName"}
    -
      service: "@service.to.third_method"
      name: "thirdMethodName"
    -
      service: "@service.to.fourth_method"
      name: ["fourthMethodName", "fourthMethodAlias"]
```
